groups:
  - name: service-alerts
    rules:
      - alert: BackendDown
        expr: up{job="backend-metrics"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Backend API is down"
          description: "The Spring Boot backend (job=backend-metrics) is not reachable by Prometheus."

      - alert: HighBackendCPU
        expr: process_cpu_seconds_total{job="backend-metrics"} > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Backend CPU usage is high"
          description: "Backend process CPU usage has exceeded 0.5 CPU-seconds over the last minute."
