- name: delete infra directory
  ansible.builtin.file:
    path: /tmp/deployment/infra
    state: absent

- name: recreate an empty infra directory
  ansible.builtin.file:
    path: /tmp/deployment/infra
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"

- name: Copy all folders except terraform
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/../"
    dest: /tmp/deployment/infra/
    rsync_opts:
      - "--exclude=terraform"
      - "--exclude=.git"
      - "--exclude=ansible"
  delegate_to: "{{ inventory_hostname }}"