- name: upload alert manager creds env file
  ansible.builtin.copy:
    dest: /tmp/deployment/infra/monitoring/alertmanager/alertmanager.yml
    content: |
      global:
        smtp_smarthost: '{{ smtp_smarthost }}'
        smtp_from: '{{ smtp_from }}'
        smtp_auth_username: '{{ smtp_auth_username }}'
        smtp_auth_password: '{{ smtp_auth_password }}'
        smtp_require_tls: true

      route:
        receiver: 'email-alerts'

      receivers:
        - name: 'email-alerts'
          email_configs:
            - to: '{{ smtp_to }}'
              send_resolved: true
    owner: "{{ ansible_user | default('deployer') }}"
    mode: '0600'
