- name: Upload Docker Compose to GCP VM
  hosts: gcp
  become: yes
  tasks:
    - name: Ensure docker  installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Ensure Docker Compose is installed
      pip:
        name: docker-compose
        executable: pip3

    - name: Remove existing compose.yml from /tmp if present
      file:
        path: /tmp/compose.yml
        state: absent

    - name: Upload compose.yml to /tmp
      copy:
        src: ./compose.yml
        dest: /tmp/compose.yml
        owner: "{{ ansible_user }}"
        mode: '0644'