- name: Upload compose file to GCP VM
  hosts: gcp
  become: yes
  tasks:
    - name: Remove any old/incorrect Docker source file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key for Debian
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Get the Debian release codename
      ansible.builtin.shell: lsb_release -cs
      register: debian_codename
      changed_when: false

    - name: Add the correct Docker repository for Debian
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ debian_codename.stdout }} stable"
        state: present
        filename: docker
        update_cache: false # We will update cache in the next task

    - name: Install packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Remove existing compose.yml from /tmp if present
      ansible.builtin.file:
        path: /tmp/compose.yml
        state: absent

    - name: Upload compose.yml to /tmp
      ansible.builtin.copy:
        src: ../compose.yml
        dest: /tmp/compose.yml
        owner: "{{ ansible_user }}"
        mode: '0644'