- name: Upload compose file to GCP VM
  hosts: gcp
  become: yes
  tasks:
    - name: delete old Docker source file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: check /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key for Debian
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Get the Debian release codename
      ansible.builtin.shell: lsb_release -cs
      register: debian_codename
      changed_when: false

    - name: Add the correct Docker repository for Debian
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ debian_codename.stdout }} stable"
        state: present
        filename: docker
        update_cache: false

    - name: Install packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Remove /tmp/deployment/infra directory
      ansible.builtin.file:
        path: /tmp/deployment/infra
        state: absent

    - name: check /tmp/deployment/infra directory exists
      ansible.builtin.file:
        path: /tmp/deployment/infra
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"

    - name: Copy infra except terraform using synchronize
      ansible.posix.synchronize:
        src: "../infra/"
        dest: "/tmp/deployment/infra/"
        recursive: true
        dirs: true
        delegate_to: localhost
        rsync_opts:
          - "--exclude=terraform/"
          - "--delete"

    - name: Set owner and mode for copied files
      ansible.builtin.file:
        path: "/tmp/deployment/infra"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        recurse: true
