- name: Upload Docker Compose to GCP VM
  hosts: gcp
  become: yes
  tasks:
    - name: Install required apt dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      shell: |
        if [ -f /etc/debian_version ]; then
          distro="debian"
        else
          distro="ubuntu"
        fi
        codename=$(lsb_release -cs)
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$distro $codename stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure Docker Engine is installed
      apt:
        name: docker-ce
        state: present

    - name: Ensure Compose is installed
      apt:
        name: docker-compose-plugin
        state: present

    - name: delete existing docker-compose.yml from /tmp if present
      file:
        path: /tmp/docker-compose.yml
        state: absent

    - name: Upload docker-compose.yml to /tmp
      copy:
        src: ./docker-compose.yml
        dest: /tmp/docker-compose.yml
        owner: "{{ ansible_user }}"
        mode: '0644'