name: Backend CI & Deploy

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: gradlew permissions
        run: chmod +x gradlew
        working-directory: ./backend

      - name: run tests
        run: ./gradlew test
        working-directory: ./backend

      - name: run checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
        working-directory: ./backend

      - name: build jar
        run: ./gradlew bootJar
        working-directory: ./backend

      - name: empty deployment directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            rm -rf /tmp/deployment/backend/*

      - name: upload Dockerfile
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: ./backend/Dockerfile
          target: /tmp/deployment/

      - name: upload build/libs
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: ./backend/build/libs
          target: /tmp/deployment/

      - name: start backend container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd /tmp/deployment/infra
            docker compose build backend
            docker compose up -d backend