name: Frontend CI & Deploy

on:
  push:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-upload-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: build frontend
        run: npm run build
        working-directory: ./frontend

      - name: delete frontend deployment directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            rm -rf /tmp/deployment/frontend/*

      - name: upload frontend
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: ./frontend/
          target: /tmp/deployment/

      - name: Start frontend container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd /tmp/deployment/infra
            docker compose build --no-cache frontend
            docker compose up -d frontend