name: deploy infra using Ansible

on:
  push:
    branches:
      - main
    paths:
      - 'infra/ansible/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Ansible
        run: pip install ansible

      - name: Create SSH key file
        run: |
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Create Ansible inventory file
        run: |
          echo "[gcp]" > inventory
          echo "${{ secrets.GCP_VM_HOST }} ansible_user=${{ secrets.GCP_VM_USER }} ansible_ssh_private_key_file=$(pwd)/id_rsa" >> inventory

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i inventory infra/ansible/playbook.yml