name: deploy infra using Ansible

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infra/ansible/**'
      - 'infra/compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Ansible
        run: pip install ansible

      - name: Create SSH key file
        run: |
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Create Ansible inventory file
        run: |
          echo "[gcp]" > inventory
          echo "${{ secrets.GCP_VM_HOST }} ansible_user=${{ secrets.GCP_VM_USER }} ansible_ssh_private_key_file=$(pwd)/id_rsa" >> inventory

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
          SMTP_AUTH_PASSWORD: ${{ secrets.SMTP_AUTH_PASSWORD }}
        run: |
          ansible-playbook -i inventory infra/ansible/playbook.yml \
            -e "smtp_smarthost=${{ secrets.SMTP_SMARTHOST }}" \
            -e "smtp_from=${{ secrets.SMTP_FROM }}" \
            -e "smtp_auth_username=${{ secrets.SMTP_AUTH_USERNAME }}" \
            -e "smtp_auth_password=${{ secrets.SMTP_AUTH_PASSWORD }}" \
            -e "smtp_to=${{ secrets.SMTP_TO }}" \
            -e "spring_datasource_url=${{ secrets.SPRING_DATASOURCE_URL }}" \
            -e "spring_datasource_username=${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
            -e "spring_datasource_password=${{ secrets.SPRING_DATASOURCE_PASSWORD }}"